### ISSUE TITLE
TODO: 디렉터리 구조 리팩토링

### ISSUE THREAD

**Issue by Sangyups** [Sangyups/career-board-notification#12]
- [x] 필요없는 백엔드 코드 삭제
- [x] `web_scapper` 폴더 내부 파일들을 최상위 디렉토리로 변경
- [x] 디렉토리 구조 변경에 따른 스크립트 수정
